/*
 * This source file was generated by the Gradle 'init' task
 */
package final_project;

public class App {
    public void startUp() {
        System.out.println("Starting Up Tic Tac Toe Game");
        GameController gameController = new GameController();
    }

    public static void main(String[] args) {
        App app = new App();
        app.startUp();
    }
}
